app:
    build: .
    environment:
        REALM: prod
        REDIS_URL: "//redis:6379"
        WEB_CONCURRENCY: 2
        MAX_REQUESTS: 2000
    links:
        - redis
    ports:
        - "8000:8000"

redis:
    image: redis
